### ISSUE TITLE
Convert to inheriting from Sinatra::Base

### ISSUE THREAD

**Issue by mattyoho** [zmcartor/lordinateuramuse#3]
When using Sinatra directly (by doing `require "sinatra"`) a couple of bad issues arise. One is the pollution of the global namespace (to make thing like `get "/foo"` available at the top level) and another is the related (relative) increase in testing difficulty. For various design and modularity reasons, it's desirable to instead have a custom application class that inherits from `Sinatra::Base`, a la:

```
require 'sinatra/base'

class MyScraperApp < Sinatra::Base

  get '/foo' do
  end

end
```

Convert the scraper app to use this style.

**Comment by zmcartor** [comment]
Refactored and updated tests to accomodate new structure.
