### ISSUE TITLE
Use a config.ru file to support running on any Rack-aware server

### ISSUE THREAD

**Issue by mattyoho** [zmcartor/lordinateuramuse#4]
Create a `config.ru` file to boot the app in any Rack-aware server. This is made easier by using the `Sinatra::Base` style of application, and is facilitated/facilitates manually configuring the Ruby load path (`$:`), which can be done in the preamble of the `config.ru` file.

**Comment by zmcartor** [comment]
Added config.ru and thin-config.yml (if appropriate.) Application runs great via thin -C thin-config.yml start
